apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These are the original YAML files you moved into the 'base' folder.
resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml